# Simple pre-commit configuration for CoreConnect
# This file exists to prevent pre-commit warnings but doesn't enforce any hooks
repos:
  - repo: local
    hooks:
      - id: no-op
        name: No operation hook (placeholder)
        entry: echo "Pre-commit configured but not enforcing any rules"
        language: system
        pass_filenames: false
