services:
  - type: web
    name: coreconnect-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false  # Set manually in Render dashboard
      - key: MONGO_DBNAME
        value: coreconnect_prod
      - key: FRONTEND_URL
        value: https://core-connects.vercel.app
      - key: RENDER_EXTERNAL_URL
        value: https://coreconnect-backend.onrender.com
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false  # Set manually
      - key: MAIL_PASSWORD
        sync: false  # Set manually
      - key: MAIL_DEFAULT_SENDER
        sync: false  # Set manually
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: MAX_LOGIN_ATTEMPTS
        value: 5
      - key: LOCKOUT_DURATION
        value: 1800
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: 900
      - key: JWT_REFRESH_TOKEN_EXPIRES
        value: 604800
