services:
  # Backend service with hot reload
  backend:
    build: 
      context: ../backend
      dockerfile: docker/Dockerfile.dev
    container_name: coreconnect-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://localhost:80,http://127.0.0.1:5173
      - FRONTEND_URL=http://localhost:5173
      - SECRET_KEY=dev-secret-key-for-docker
      - JWT_SECRET_KEY=dev-jwt-secret-key-for-docker
      - MONGO_URI=mongodb+srv://arunkumar:Lfe1tt3AGeCk8WAQ@coreconnect.4gocxxb.mongodb.net/coreconnect_dev?retryWrites=true&w=majority
      - MONGO_DBNAME=coreconnect_dev
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=learnarun10@gmail.com
      - MAIL_PASSWORD=Ganpati@10k
      - MAIL_DEFAULT_SENDER=learnarun10@gmail.com
    volumes:
      - ../backend:/app
      - /app/__pycache__
      - /app/.venv
    restart: unless-stopped
    command: python app.py
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service with hot reload (Vite dev server)
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.dev
    container_name: coreconnect-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 5173
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
