services:
  # Backend service
  backend:
    build: 
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: coreconnect-backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - API_VERSION=v1
    volumes:
      - ../backend:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    container_name: coreconnect-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


