name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday
  workflow_dispatch: # Manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Update Python dependencies
      working-directory: ./backend
      run: |
        pip install --upgrade pip pip-tools
        pip-compile --upgrade requirements.in || echo "No requirements.in found"
    
    - name: Update Node.js dependencies
      working-directory: ./frontend
      run: |
        npm update
        npm audit fix --force || true
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          Automated dependency updates
          
          - Updated Python packages
          - Updated Node.js packages
          - Fixed security vulnerabilities where possible
        branch: dependency-updates
        delete-branch: true
